Dockerfile
functional tests:
```
docker build -t autograph-edge:build .
docker run autograph-edge:build
{"Timestamp":1532629028934534626,"Time":"2018-07-26T18:17:08Z","Type":"app.log","Logger":"autograph-edge","Hostname":"5096a850094d","EnvVersion":"2.0","Pid":8,"Severity":4,"Fields":{"msg":"start server on port 8080"}}
```
r? @milescrabill
=> dockerfile: don't remove libltdl-dev

main.go
fixes: #10 
This allows me to test autograph and autograph edge against encrypted configs without decrypting them (which comes up when adding a new APK key). Might be useful for CI too.
r? @ajvb or @jvehent 
I think AJ needs to be adding as a collaborator.
Functional Tests:
```
autograph-edge autograph-edge.yaml
{"Timestamp":1535393020167093194,"Time":"2018-08-27T18:03:40Z","Type":"app.log","Logger":"autograph-edge","Hostname":"gguthe-ThinkPad-X1-Carbon-6th","EnvVersion":"2.0","Pid":21642,"Severity":4,"Fields":{"msg":"start server on port 8080 with upstream autograph http://localhost:8000/sign/file"}}
```
```
autograph-edge -u https://example.com:9090/flo/blog autograph-edge.yaml
{"Timestamp":1535393053032429851,"Time":"2018-08-27T18:04:13Z","Type":"app.log","Logger":"autograph-edge","Host …
```
=> main: add optional autograph url param

.circleci/config.yml, .dockerignore, Dockerfile, docker-compose.yml
fixes: #8 
reduce docker image size 52% from [~600MB](https://hub.docker.com/r/mozilla/autographedge/tags/?page=1&ordering=last_updated) to ~288MB which is smaller than the latest autograph image of [~544MB](https://hub.docker.com/r/mozilla/autograph/tags/?page=1&ordering=last_updated) using multi-stage builds and switching from golang to debian images and the debian slim variant.
Functional tests:
=> Reduce image size

README.md, autograph-edge.yaml, main.go, main_test.go
Fixes: #12 
Changes:
* **breaking** rename `token` to `client_token` in auth config
* validate auth client token length; validate other required auth fields are not empty
=> rename token to client_token

.gitignore, main_test.go
Changes:
* make authorize and heartbeat tests table-based
* load the local `autograph-edge.yaml` config (with modules the latest version isn't necessarily at `$GOPATH/src/go.mozilla.org/autograph-edge/`)
=> Refactor tests

autograph-edge.yaml, client.go, docker-compose.yml, main.go, main_test.go
Changes:
* **breaking** change for v2 rename config `url` to `autograph_base_url` and `conf.URL` to `conf.BaseURL`
=> rename config url to autograph_base_url

.circleci/config.yml
fix: #237 
Changes:
* run `make test` in a new unit-test CI job
* track coverage on coveralls
=> Fix 237 track coverage

Dockerfile
Reverts mozilla-services/autograph-edge#271 -- hwine forgot that we are in maintenance mode.
=> Revert "Bump golang from 1.17.3-buster to 1.17.6-buster"

integration_test/Dockerfile
Migrating to newer release is a project for the future.
Fixes #305
=> Support debian stretch past EOL for test harness

.circleci/config.yml, Dockerfile, go.mod
I've done my best to pull in the enhancements and style changes made to autograph in https://github.com/mozilla-services/autograph/pull/898 over here as well.
Unlike that repo, this required no changes to bring up to the latest stable go version - so I've done that as part of this (we had to upgrade to _some_ new version, so there was no reason to pull in the latest).
It also necessitated changing images and docker versions in the CircleCI jobs, which required some small tweaks to their payloads. There might be other changes we want to make there, but I'm trying to keep this as minimal as possible for now.
=> AUT-124: update to debian bookworm & golang 1.22.5

.github/CODEOWNERS
This is the same as what we've [added in the main Autograph repo](https://github.com/mozilla-services/autograph/pull/922) except there's no need to look in addons folks.
=> add a CODEOWNERS file

docker-compose.yml, integration_test/sign_test_apk.sh, integration_test/sign_test_xpi.sh
This replaces both the `links` defined and the waiting we do in the test script.
=> Add healthchecks for autograph & autograph-edge in docker-compose.yml

.circleci/config.yml
This upgrades the build & deploy images used in circleci to modern, supported ones. I also happened to notice that we accidentally lost dockerhub pushes to the `latest` tag when this repo moved from `master` to `main`.
=> AUT-134: chore: upgrade build & deploy images used in circleci

.circleci/config.yml
Should've caught this in https://github.com/mozilla-services/autograph-edge/pull/321...but I didn't.
Same as #322, except this one will run CI!
=> fix: deploy to `latest` tag in circleci on pushes to `main`

go.mod, go.sum
This is replacing an old dependabot PR from last year that's apparently
lost its state. See
https://github.com/mozilla-services/autograph-edge/pull/302
Dependabot won't recreate the PR, so we do it for it.
=> bump sirupsen/logrus from 1.8.1 to v1.9.3

.circleci/config.yml
This is breaking the CI and we don't pay attention to this closely right
now.
Updates AUT-213
=> remove coveralls coverage stats upload

.github/workflows/tests.yaml, main_test.go
This creates a github workflow to run the unit and integration tests for pull requests and on merge to the `main` branch.
Along the way we also encountered a flaky test that needed fixing. In particular connections to `http://localhost:8000` don't result in deterministic error messages because `localhost` can resolve to either `127.0.0.1` or `[::]`. To get a consistent result we needed to force the tests to use a fixed localhost address.
=> AUT-105: GitHub workflow for testing

version.sh
I must sheepishly admit that I YOLO'ed my last PR a little too quickly and never noticed that `version.sh` was generating invalid JSON. (And I am kinda surprised that there wasn't any test to catch it).
This should correct the generated version file so that it is parseable as valid JSON.
=> Fix malformed version.json generation

.github/workflows/deploy.yaml
This change gives us separate tags for prereleases and releases, which will allow our deployment pipeline to separate out stage & production deploys.
I've also adjusted the `latest` tag to only be used on pushes to main, rather than all deployments. This will ensure that any ongoing dev work against main won't be disrupted if we cut a release.
Here's some example runs in my own repo (they fail, but the important part is the metadata step):
* [A push to main](https://github.com/bhearsum/autograph-edge/actions/runs/11298955041/job/31428961407), which just generates a `latest` tag
* [Publishing the `1.1.1` prerelease](https://github.com/bhearsum/autograph-edge/actions/runs/11298968687/job/31428998722) just generates a `1.1.1-prerelease` tag
* [Republishing `1.1.1` as a full …
=> AUT-271: make separate tags and docker images pushes for production deploys of autograph-edge

.github/workflows/deploy.yaml
This is a port of
https://github.com/mozilla-services/autograph/pull/1063 (and
https://github.com/mozilla-services/autograph/pull/1060).
Currently, we're doing a deploy to one of our staging environments on
every merge to main this repo. That wasn't desired.
Along the way, we also build arm64 versions of the docker image for
convenience. See https://github.com/mozilla-services/autograph/pull/1059
=> correct accidental continous deploys

Makefile
In https://github.com/mozilla-services/autograph-edge/pull/337, we
reference `make generate` like in the autograph repo.
But here that was called `make version.json`. For consistency, and any
possible (though, unlikely) additions to what needs to be generate, we
rename the make target to `generate` and leave the deploy workflow
alone.
=> correct deploy workflows by renaming generate target
